def parse_intent(message: str) -> str:
    task_keywords = [
        "rag",
        "RAG",
        "知识库",
        "向量",
        "流程",
        "上传",
        "文档",
        "资料",
        "检索",
        "搜索",
        "联网",
        "网上",
        "网页",
        "最新",
        "新闻",
        "天气",
        "时间",
        "地点",
        "B站",
        "b站",
        "哔哩哔哩",
        "bilibili",
        "热门视频",
        "综合热门",
        "网易云",
        "网易云音乐",
        "飙升榜",
        "榜单",
        "项目",
        "分析",
        "总结",
    ]
    return "task" if any(keyword in message for keyword in task_keywords) else "chitchat"
